### PR TITLE
Update Clojure and a few cosmetic changes

### PR DESCRIPTION
**Pull request by bsima**
This is a great library and I'm testing it out for use in production. I've got a few changes that I'd like, mostly cosmetic. Nothing here changes the functionality. 

Let me know if you want me to do anything else before getting this merged upstream.

Edit: I would have signed all my commits but magit didn't pick up my git settings :rage: and I didn't notice until the last commit grrr

### CODE REVIEW

**Comment by mattiasholmqvist** [comment]
Hi Ben!

Cool to see that you like my small library. 👍 I'm merging your changes right away. Thanks for the cleanup!

Let me know how it works out for you and if you're missing anything else.

**Comment by bsima** [comment]
@mattiasholmqvist awesome, thanks for the quick reply! I might have some additional PRs as I start using evently in real code.

Might I also suggest bumping the version number to 0.1.1 and putting this on Clojars? From what I can tell this isn't up there yet -> https://clojars.org/search?q=evently

**Comment by mattiasholmqvist** [comment]
Absolutely!

Sounds great! Will put it up on clojars as soon as possible!

Skickat från min iPhone

**Comment by mattiasholmqvist** [comment]
Try this now:

https://clojars.org/evently

/Mattias

**Comment by bsima** [comment]
woot woot!! thanks mattias!

**Pull request merged**
