### PR TITLE
Add spec

### PR DESCRIPTION
**Pull request by bsima**

### CODE REVIEW

**Comment by bsima** [comment]
Status update: I'm waiting for Clojure 1.9 to be released, since in the alpha versions currently available the clojure.spec API is changing a lot. 

Also, for some reason all the spec tests fail from `lein test` at the command line, but they pass at the repl. Don't know why, but I'll look into it again when 1.9 is released.

**Comment by mattiasholmqvist** [comment]
No problem. Keep me posted. Will be offline for a while during july in case I'm not responding, so you know!

Mattias

Skickat från min iPhone

**Comment by bsima** [comment]
This could be the reason the tests were failing from the CLI and not from the REPL: https://www.bountysource.com/issues/36003731-leiningen-test-hooks-clash-with-test-check-0-9-0

**Edit:** this is definitely the reason. I switched to [boot](https://boot-clj.com) and the tests pass fine...

**Comment by bsima** [comment]
Awesome, switching to boot made the tests pass! This is almost good to go...

**Pull request closed without merging**
